-- Phase 2: Subscription infrastructure
-- pattern_profiles, daily_entries, monthly_reports, subscriptions, detected_patterns

-- ── pattern_profiles ───────────────────────────────────────────────
create table if not exists pattern_profiles (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users(id) on delete cascade,
  report_id       uuid references reports(id),
  email           text,
  first_name      text,

  -- Baseline from initial report (never changes)
  baseline_energy_cycle   text,
  baseline_growth_pattern text,
  baseline_risk_pattern   text,

  -- Living context (updated daily/weekly)
  current_season  text,                      -- spring|summer|autumn|winter
  streak_days     int     not null default 0,
  last_entry_date date,

  -- Compressed AI context (JSONB arrays, bounded size)
  recurring_patterns  jsonb not null default '[]', -- max 10 RecurringPattern
  active_alerts       jsonb not null default '[]', -- current Alert[]
  milestones          jsonb not null default '[]', -- max 20 Milestone

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint profile_user_or_email check (user_id is not null or email is not null)
);

alter table pattern_profiles enable row level security;
create policy "Users see own profile"
  on pattern_profiles for select
  using (auth.uid() = user_id);
create policy "Service role full access profiles"
  on pattern_profiles for all
  using (true)
  with check (true);

-- ── daily_entries ──────────────────────────────────────────────────
create table if not exists daily_entries (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  entry_date    date not null,

  energy_score  int  not null check (energy_score between 1 and 10),
  mood          text not null,      -- thriving|steady|struggling|drained
  focus_area    text,               -- optional: what they're working on
  note          text,               -- optional free text (max 300 chars enforced at API layer)

  -- Generated by Level 1 AI (Haiku) — cached, never regenerated for same date
  daily_insight text,

  created_at    timestamptz not null default now(),

  unique (user_id, entry_date)
);

alter table daily_entries enable row level security;
create policy "Users see own entries"
  on daily_entries for select
  using (auth.uid() = user_id);
create policy "Users insert own entries"
  on daily_entries for insert
  with check (auth.uid() = user_id);
create policy "Service role full access entries"
  on daily_entries for all
  using (true)
  with check (true);

create index if not exists idx_daily_entries_user_date
  on daily_entries (user_id, entry_date desc);

-- ── monthly_reports ────────────────────────────────────────────────
create table if not exists monthly_reports (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  report_month  date not null,              -- first day of month, e.g. 2026-05-01

  -- Generated by Level 2 AI (Sonnet)
  summary       text,
  pattern_shift text,
  next_month    text,
  full_report   jsonb,

  generated_at  timestamptz,
  created_at    timestamptz not null default now(),

  unique (user_id, report_month)
);

alter table monthly_reports enable row level security;
create policy "Users see own monthly reports"
  on monthly_reports for select
  using (auth.uid() = user_id);
create policy "Service role full access monthly"
  on monthly_reports for all
  using (true)
  with check (true);

create index if not exists idx_monthly_reports_user_month
  on monthly_reports (user_id, report_month desc);

-- ── subscriptions ──────────────────────────────────────────────────
create table if not exists subscriptions (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid references auth.users(id),   -- nullable: backfilled on first login
  email                 text unique not null,

  -- Lemon Squeezy data
  ls_subscription_id    text unique,
  ls_order_id           text,
  ls_customer_id        text,
  ls_variant_id         text,

  status                text not null default 'active'
                          check (status in ('active','cancelled','past_due','paused','expired')),
  plan                  text not null default 'monthly'
                          check (plan in ('monthly','annual')),

  current_period_start  timestamptz,
  current_period_end    timestamptz,
  cancelled_at          timestamptz,

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

alter table subscriptions enable row level security;
create policy "Users see own subscription"
  on subscriptions for select
  using (auth.uid() = user_id);
create policy "Service role full access subscriptions"
  on subscriptions for all
  using (true)
  with check (true);

-- ── detected_patterns ──────────────────────────────────────────────
create table if not exists detected_patterns (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,

  pattern_type  text not null,     -- e.g. "energy_cycle", "risk_trigger", "growth_condition"
  title         text not null,
  description   text not null,
  evidence      jsonb not null default '[]',  -- list of entry_date strings that support it
  confidence    numeric(3,2) check (confidence between 0 and 1),
  is_active     boolean not null default true,

  first_seen    date,
  last_updated  date,
  created_at    timestamptz not null default now()
);

alter table detected_patterns enable row level security;
create policy "Users see own patterns"
  on detected_patterns for select
  using (auth.uid() = user_id);
create policy "Service role full access patterns"
  on detected_patterns for all
  using (true)
  with check (true);

create index if not exists idx_detected_patterns_user
  on detected_patterns (user_id);

-- ── updated_at triggers ────────────────────────────────────────────
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_pattern_profiles_updated_at
  before update on pattern_profiles
  for each row execute procedure set_updated_at();

create trigger trg_subscriptions_updated_at
  before update on subscriptions
  for each row execute procedure set_updated_at();
